# Generated by Django 5.0.7 on 2024-07-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_login_password_alter_login_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='username',
            new_name='email',
        ),
    ]
